### PR TITLE
feat: setup project structure

### PR DESCRIPTION
**Pull request by BenitoVisone**
This **PR** will add bootstrap structure for `1id` project:

- Maven modules hierarchy for all AWS resources
  - `1id-ecs-core`
  - `1id-lambda-client-registration`
  - `1id-lambda-service-metadata`
- Packages definition
- Example modules dependency
- Example dockerfiles

### CODE REVIEW

**Review by GiuMontesano — APPROVED** [review]
LGTM

**Review by giuseppe-gangemi — APPROVED** [review]
lgtm

**Comment by uolter** [comment]
@BenitoVisone @giuseppe-gangemi @GiuMontesano it is right to release the .mvn dir ?
32 file changes ????

**Review by GiuMontesano — APPROVED** [review]
LGTM

**Pull request merged**
